/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  iCloudUsername: "",
  iCloudPassword: "",
  calendarName: "",
  dailyNoteFormat: "YYYY-MM-DD",
  dailyNoteFolder: ""
};
var VIEW_TYPE = "obsidian-cal-view";
function simpleWeekInfo(sunday) {
  const saturday = new Date(sunday);
  saturday.setDate(sunday.getDate() + 6);
  let year = sunday.getFullYear();
  if (saturday.getMonth() === 0 && saturday.getFullYear() === year + 1) {
    year = year + 1;
  }
  const jan1 = new Date(year, 0, 1);
  const week1Start = new Date(year, 0, 1 - jan1.getDay());
  const diffDays = Math.round((sunday.getTime() - week1Start.getTime()) / 864e5);
  const weekNum = Math.floor(diffDays / 7) + 1;
  return { weekYear: year, weekNum };
}
function formatDate(date, fmt) {
  return fmt.replace("YYYY", String(date.getFullYear())).replace("MM", String(date.getMonth() + 1).padStart(2, "0")).replace("DD", String(date.getDate()).padStart(2, "0"));
}
function pad2(n) {
  return String(n).padStart(2, "0");
}
function formatTime(date) {
  return `${pad2(date.getHours())}:${pad2(date.getMinutes())}`;
}
function formatEventDate(date) {
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const yyyy = String(date.getFullYear()).slice(-4);
  return `${months[date.getMonth()]} ${date.getDate()}, ${yyyy}`;
}
var DAY_NAMES = ["SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY"];
var DOW_LABELS = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];
function sameDay(a, b) {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}
function toCalDAVDate(date) {
  return `${date.getUTCFullYear()}${pad2(date.getUTCMonth() + 1)}${pad2(date.getUTCDate())}T000000Z`;
}
function unescapeICalText(s) {
  return s.replace(/\\,/g, ",").replace(/\\;/g, ";").replace(/\\n/g, "\n").replace(/\\\\/g, "\\");
}
function parseICalDate(value, params) {
  const isAllDay = params.includes("VALUE=DATE") || /^\d{8}$/.test(value);
  if (isAllDay) {
    const yr2 = parseInt(value.slice(0, 4));
    const mo2 = parseInt(value.slice(4, 6)) - 1;
    const dy2 = parseInt(value.slice(6, 8));
    return { date: new Date(yr2, mo2, dy2, 0, 0, 0), isAllDay: true };
  }
  if (value.endsWith("Z")) {
    const yr2 = parseInt(value.slice(0, 4));
    const mo2 = parseInt(value.slice(4, 6)) - 1;
    const dy2 = parseInt(value.slice(6, 8));
    const hr2 = parseInt(value.slice(9, 11));
    const mn2 = parseInt(value.slice(11, 13));
    const sc2 = parseInt(value.slice(13, 15));
    return { date: new Date(Date.UTC(yr2, mo2, dy2, hr2, mn2, sc2)), isAllDay: false };
  }
  const yr = parseInt(value.slice(0, 4));
  const mo = parseInt(value.slice(4, 6)) - 1;
  const dy = parseInt(value.slice(6, 8));
  const hr = parseInt(value.slice(9, 11));
  const mn = parseInt(value.slice(11, 13));
  const sc = parseInt(value.slice(13, 15));
  return { date: new Date(yr, mo, dy, hr, mn, sc), isAllDay: false };
}
function parseICalEvents(icalText) {
  var _a, _b, _c, _d;
  const unfolded = icalText.replace(/\r\n/g, "\n").replace(/\n[ \t]/g, "");
  const lines = unfolded.split("\n");
  const events = [];
  let inEvent = false;
  let cur = { categories: [] };
  for (const raw of lines) {
    const line = raw.trim();
    if (line === "BEGIN:VEVENT") {
      inEvent = true;
      cur = { categories: [], hasAlarm: false };
      continue;
    }
    if (line === "END:VEVENT") {
      if (cur.summary && cur.start) {
        events.push({
          uid: (_a = cur.uid) != null ? _a : "",
          summary: cur.summary,
          start: cur.start,
          end: (_b = cur.end) != null ? _b : cur.start,
          isAllDay: (_c = cur.isAllDay) != null ? _c : false,
          hasAlarm: (_d = cur.hasAlarm) != null ? _d : false,
          categories: cur.categories
        });
      }
      inEvent = false;
      cur = { categories: [] };
      continue;
    }
    if (!inEvent)
      continue;
    if (line === "BEGIN:VALARM") {
      cur.hasAlarm = true;
      continue;
    }
    const colonIdx = line.indexOf(":");
    if (colonIdx < 0)
      continue;
    const propFull = line.slice(0, colonIdx);
    const value = line.slice(colonIdx + 1);
    const semiIdx = propFull.indexOf(";");
    const propName = semiIdx >= 0 ? propFull.slice(0, semiIdx) : propFull;
    const params = semiIdx >= 0 ? propFull.slice(semiIdx + 1) : "";
    switch (propName) {
      case "UID":
        cur.uid = value;
        break;
      case "SUMMARY":
        cur.summary = unescapeICalText(value);
        break;
      case "CATEGORIES":
        cur.categories = value.split(",").map((c) => c.trim()).filter(Boolean);
        break;
      case "DTSTART": {
        const p = parseICalDate(value, params);
        cur.start = p.date;
        cur.isAllDay = p.isAllDay;
        break;
      }
      case "DTEND": {
        cur.end = parseICalDate(value, params).date;
        break;
      }
    }
  }
  return events;
}
var CalDAVClient = class {
  constructor(settings) {
    this.baseUrl = "https://caldav.icloud.com";
    this.calendarUrl = null;
    this.settings = settings;
  }
  authHeader() {
    return "Basic " + btoa(`${this.settings.iCloudUsername}:${this.settings.iCloudPassword}`);
  }
  resolveUrl(href) {
    if (href.startsWith("http://") || href.startsWith("https://"))
      return href;
    if (href.startsWith("/")) {
      const u = new URL(this.baseUrl);
      return `${u.protocol}//${u.host}${href}`;
    }
    return `${this.baseUrl.replace(/\/$/, "")}/${href}`;
  }
  // Extract text from the first XML element matching localName (namespace-agnostic)
  xmlText(xmlText, localName) {
    const re = new RegExp(`<[^>]*:?${localName}[^>]*>([\\s\\S]*?)<\\/[^>]*:?${localName}>`, "i");
    const m = xmlText.match(re);
    return m ? m[1].trim() : null;
  }
  // Extract all <href> values inside each <response>
  xmlAllHrefs(xml) {
    const results = [];
    const responseRe = /<[^>]*:?response[^>]*>([\s\S]*?)<\/[^>]*:?response>/gi;
    let m;
    while ((m = responseRe.exec(xml)) !== null) {
      const block = m[1];
      const hrefMatch = block.match(/<[^>]*:?href[^>]*>([\s\S]*?)<\/[^>]*:?href>/i);
      const nameMatch = block.match(/<[^>]*:?displayname[^>]*>([\s\S]*?)<\/[^>]*:?displayname>/i);
      if (hrefMatch) {
        results.push({
          href: hrefMatch[1].trim(),
          displayName: nameMatch ? nameMatch[1].trim() : ""
        });
      }
    }
    return results;
  }
  // Extract all calendar-data blocks from a REPORT response
  xmlCalendarData(xml) {
    const data = [];
    const re = /<[^>]*:?calendar-data[^>]*>([\s\S]*?)<\/[^>]*:?calendar-data>/gi;
    let m;
    while ((m = re.exec(xml)) !== null) {
      const raw = m[1].replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&").replace(/&quot;/g, '"');
      data.push(raw);
    }
    return data;
  }
  async discoverCalendarUrl() {
    var _a, _b, _c, _d, _e, _f, _g;
    const resp1 = await (0, import_obsidian.requestUrl)({
      url: `${this.baseUrl}/`,
      method: "PROPFIND",
      headers: {
        Authorization: this.authHeader(),
        Depth: "0",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<d:propfind xmlns:d="DAV:">
  <d:prop><d:current-user-principal/></d:prop>
</d:propfind>`
    });
    const principalHref = (_d = (_c = (_b = (_a = this.xmlText(resp1.text, "current-user-principal")) == null ? void 0 : _a.match(/<[^>]*:?href[^>]*>([\s\S]*?)<\/[^>]*:?href>/i)) == null ? void 0 : _b[1]) == null ? void 0 : _c.trim()) != null ? _d : this.xmlText(resp1.text, "href");
    if (!principalHref)
      throw new Error("Could not find iCloud user principal. Check username/password.");
    const resp2 = await (0, import_obsidian.requestUrl)({
      url: this.resolveUrl(principalHref),
      method: "PROPFIND",
      headers: {
        Authorization: this.authHeader(),
        Depth: "0",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
  <d:prop><c:calendar-home-set/></d:prop>
</d:propfind>`
    });
    const homeHref = (_g = (_f = (_e = this.xmlText(resp2.text, "calendar-home-set")) == null ? void 0 : _e.match(/<[^>]*:?href[^>]*>([\s\S]*?)<\/[^>]*:?href>/i)) == null ? void 0 : _f[1]) == null ? void 0 : _g.trim();
    if (!homeHref)
      throw new Error("Could not find iCloud calendar home. Check credentials.");
    const resp3 = await (0, import_obsidian.requestUrl)({
      url: this.resolveUrl(homeHref),
      method: "PROPFIND",
      headers: {
        Authorization: this.authHeader(),
        Depth: "1",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
  <d:prop>
    <d:displayname/>
    <d:resourcetype/>
  </d:prop>
</d:propfind>`
    });
    const calendars = this.xmlAllHrefs(resp3.text);
    const target = this.settings.calendarName.toLowerCase().trim();
    const found = calendars.find((c) => c.displayName.toLowerCase().trim() === target);
    if (!found) {
      const names = calendars.map((c) => `"${c.displayName}"`).join(", ");
      throw new Error(
        `Calendar "${this.settings.calendarName}" not found.
Available: ${names || "(none)"}`
      );
    }
    return this.resolveUrl(found.href);
  }
  async fetchEvents(year, month) {
    if (!this.calendarUrl) {
      this.calendarUrl = await this.discoverCalendarUrl();
    }
    const firstOfMonth = new Date(year, month, 1);
    const lastOfMonth = new Date(year, month + 1, 0);
    const gridStart = new Date(firstOfMonth);
    gridStart.setDate(gridStart.getDate() - gridStart.getDay());
    const gridEnd = new Date(lastOfMonth);
    gridEnd.setDate(gridEnd.getDate() + (6 - gridEnd.getDay()) + 1);
    const startStr = toCalDAVDate(gridStart);
    const endStr = toCalDAVDate(gridEnd);
    const resp = await (0, import_obsidian.requestUrl)({
      url: this.calendarUrl,
      method: "REPORT",
      headers: {
        Authorization: this.authHeader(),
        Depth: "1",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <D:getetag/>
    <C:calendar-data/>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range start="${startStr}" end="${endStr}"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>`
    });
    const icalBlocks = this.xmlCalendarData(resp.text);
    const events = [];
    for (const block of icalBlocks) {
      events.push(...parseICalEvents(block));
    }
    return events;
  }
  // Call this when settings change so we re-discover on next fetch
  reset() {
    this.calendarUrl = null;
  }
};
var ConfirmCreateModal = class extends import_obsidian.Modal {
  constructor(app, message, onConfirm) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "Note not found" });
    contentEl.createEl("p", { text: this.message });
    const btnRow = contentEl.createDiv({ cls: "modal-button-container" });
    const yes = btnRow.createEl("button", { text: "Create", cls: "mod-cta" });
    yes.onclick = () => {
      this.close();
      this.onConfirm();
    };
    const no = btnRow.createEl("button", { text: "Cancel" });
    no.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CalendarView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.eventCache = /* @__PURE__ */ new Map();
    // "YYYY-M" → events
    this.isLoading = false;
    this.lastError = "";
    this.plugin = plugin;
    const now = new Date();
    this.selectedDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    this.displayMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Calendar";
  }
  getIcon() {
    return "calendar";
  }
  async onOpen() {
    this.containerEl.addClass("cal-root");
    await this.render();
    this.loadEventsForMonth(this.displayMonth.getFullYear(), this.displayMonth.getMonth());
  }
  onClose() {
    return Promise.resolve();
  }
  // Public: force refresh (called after settings change)
  async refresh() {
    this.eventCache.clear();
    await this.render();
    this.loadEventsForMonth(this.displayMonth.getFullYear(), this.displayMonth.getMonth());
  }
  cacheKey(year, month) {
    return `${year}-${month}`;
  }
  async loadEventsForMonth(year, month) {
    const s = this.plugin.settings;
    if (!s.iCloudUsername || !s.iCloudPassword || !s.calendarName)
      return;
    const key = this.cacheKey(year, month);
    if (this.eventCache.has(key))
      return;
    this.isLoading = true;
    this.lastError = "";
    this.render();
    try {
      const events = await this.plugin.caldav.fetchEvents(year, month);
      this.eventCache.set(key, events);
      this.lastError = "";
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      this.lastError = msg;
      new import_obsidian.Notice(`Calendar: ${msg}`, 8e3);
    } finally {
      this.isLoading = false;
      this.render();
    }
  }
  eventsForDate(date) {
    var _a;
    const key = this.cacheKey(date.getFullYear(), date.getMonth());
    const all = (_a = this.eventCache.get(key)) != null ? _a : [];
    return all.filter((e) => {
      if (e.isAllDay)
        return sameDay(e.start, date);
      return sameDay(e.start, date);
    }).sort((a, b) => {
      if (a.isAllDay && !b.isAllDay)
        return -1;
      if (!a.isAllDay && b.isAllDay)
        return 1;
      return a.start.getTime() - b.start.getTime();
    });
  }
  hasEvents(date) {
    const key = this.cacheKey(date.getFullYear(), date.getMonth());
    if (!this.eventCache.has(key))
      return false;
    return this.eventsForDate(date).length > 0;
  }
  async render() {
    const { contentEl } = this;
    contentEl.empty();
    const container = contentEl.createDiv({ cls: "cal-container" });
    this.renderHeader(container);
    this.renderGrid(container);
    container.createDiv({ cls: "cal-separator" });
    this.renderEventSection(container);
  }
  // ---- Header ----
  renderHeader(parent) {
    const header = parent.createDiv({ cls: "cal-header" });
    const yr = this.displayMonth.getFullYear();
    const mo = this.displayMonth.getMonth();
    header.createDiv({ cls: "cal-title", text: `${yr}-${pad2(mo + 1)}` });
    const nav = header.createDiv({ cls: "cal-nav" });
    const prev = nav.createEl("button", { cls: "cal-nav-btn", text: "\u2039" });
    prev.title = "Previous month";
    prev.onclick = () => this.navigateMonth(-1);
    const next = nav.createEl("button", { cls: "cal-nav-btn", text: "\u203A" });
    next.title = "Next month";
    next.onclick = () => this.navigateMonth(1);
  }
  navigateMonth(delta) {
    const d = this.displayMonth;
    this.displayMonth = new Date(d.getFullYear(), d.getMonth() + delta, 1);
    this.render();
    this.loadEventsForMonth(this.displayMonth.getFullYear(), this.displayMonth.getMonth());
  }
  // ---- Calendar grid ----
  renderGrid(parent) {
    var _a;
    const grid = parent.createDiv({ cls: "cal-grid" });
    grid.createDiv({ cls: "cal-grid-header-cw", text: "W" });
    DOW_LABELS.forEach((label, i) => {
      const el = grid.createDiv({ cls: "cal-dow-label" + (i === 0 ? " cal-sunday" : "") });
      el.setText(label);
    });
    const today = new Date();
    const year = this.displayMonth.getFullYear();
    const month = this.displayMonth.getMonth();
    const gridStart = new Date(year, month, 1);
    gridStart.setDate(gridStart.getDate() - gridStart.getDay());
    const lastOfMonth = new Date(year, month + 1, 0);
    for (let week = 0; week < 6; week++) {
      const sunday = new Date(gridStart);
      sunday.setDate(gridStart.getDate() + week * 7);
      if (week > 0 && sunday > lastOfMonth)
        break;
      const { weekYear, weekNum } = simpleWeekInfo(sunday);
      const wnCell = grid.createDiv({ cls: "cal-week-num", text: String(weekNum) });
      wnCell.title = `Open weekly note ${weekYear}-W${pad2(weekNum)}`;
      wnCell.onclick = () => this.openWeeklyNote(weekYear, weekNum);
      for (let dow = 0; dow < 7; dow++) {
        const cellDate = new Date(sunday);
        cellDate.setDate(sunday.getDate() + dow);
        const isOtherMonth = cellDate.getMonth() !== month;
        const isToday = sameDay(cellDate, today);
        const isSelected = sameDay(cellDate, this.selectedDate);
        const isSunday = dow === 0;
        let cls = "cal-day-cell";
        if (isOtherMonth)
          cls += " cal-other-month";
        if (isToday)
          cls += " cal-today";
        if (isSelected)
          cls += " cal-selected";
        if (isSunday)
          cls += " cal-sunday";
        const cell = grid.createDiv({ cls });
        const numEl = cell.createDiv({ cls: "cal-day-num" });
        numEl.setText(String(cellDate.getDate()));
        const dotsEl = cell.createDiv({ cls: "cal-day-dots" });
        const evs = this.eventsForDate(cellDate);
        const maxDots = 3;
        const dotsCount = Math.min(evs.length, maxDots);
        for (let d = 0; d < dotsCount; d++) {
          const dot = dotsEl.createDiv({ cls: "cal-dot" });
          if ((_a = evs[d]) == null ? void 0 : _a.isAllDay)
            dot.addClass("cal-allday");
        }
        const dateCopy = new Date(cellDate);
        cell.onclick = () => this.selectDate(dateCopy);
      }
    }
  }
  // ---- Event section ----
  renderEventSection(parent) {
    const section = parent.createDiv({ cls: "cal-event-section" });
    const sectionHeader = section.createDiv({ cls: "cal-event-section-header" });
    sectionHeader.createSpan({ cls: "cal-event-section-title", text: "Event List" });
    const listEl = section.createDiv({ cls: "cal-event-list" });
    const dayHeader = listEl.createDiv({ cls: "cal-event-day-header" });
    dayHeader.createSpan({
      cls: "cal-event-day-name",
      text: DAY_NAMES[this.selectedDate.getDay()]
    });
    dayHeader.createSpan({
      cls: "cal-event-date-label",
      text: formatEventDate(this.selectedDate)
    });
    const s = this.plugin.settings;
    if (!s.iCloudUsername || !s.iCloudPassword || !s.calendarName) {
      const status = listEl.createDiv({ cls: "cal-status" });
      status.setText("Configure iCloud credentials in Settings to see events.");
      return;
    }
    if (this.isLoading) {
      listEl.createDiv({ cls: "cal-status", text: "Loading events\u2026" });
      return;
    }
    if (this.lastError) {
      const errEl = listEl.createDiv({ cls: "cal-status cal-error" });
      errEl.setText(`Error: ${this.lastError}`);
      const retryBtn = listEl.createEl("button", { cls: "cal-refresh-btn", text: "Retry" });
      retryBtn.onclick = () => {
        this.plugin.caldav.reset();
        this.eventCache.clear();
        this.loadEventsForMonth(this.displayMonth.getFullYear(), this.displayMonth.getMonth());
      };
      return;
    }
    const key = this.cacheKey(this.selectedDate.getFullYear(), this.selectedDate.getMonth());
    if (!this.eventCache.has(key)) {
      listEl.createDiv({ cls: "cal-status", text: "Loading events\u2026" });
      return;
    }
    const events = this.eventsForDate(this.selectedDate);
    const allCats = /* @__PURE__ */ new Set();
    events.forEach((e) => e.categories.forEach((c) => allCats.add(c)));
    if (allCats.size > 0) {
      const tagsEl = listEl.createDiv({ cls: "cal-tags" });
      allCats.forEach((cat) => tagsEl.createSpan({ cls: "cal-tag", text: cat }));
    }
    if (events.length === 0) {
      listEl.createDiv({ cls: "cal-status", text: "No events for this day." });
      return;
    }
    for (const ev of events) {
      const item = listEl.createDiv({ cls: "cal-event-item" });
      item.createDiv({ cls: "cal-event-bullet" });
      const content = item.createDiv({ cls: "cal-event-content" });
      if (ev.isAllDay) {
        content.createDiv({ cls: "cal-event-allday-label", text: "All day" });
      } else {
        const timeText = `${formatTime(ev.start)} \u2013 ${formatTime(ev.end)}${ev.hasAlarm ? "  \u23F0" : ""}`;
        content.createDiv({ cls: "cal-event-time", text: timeText });
      }
      content.createDiv({ cls: "cal-event-title", text: ev.summary });
    }
  }
  // ---- Select a date & open daily note ----
  async selectDate(date) {
    this.selectedDate = date;
    if (date.getFullYear() !== this.displayMonth.getFullYear() || date.getMonth() !== this.displayMonth.getMonth()) {
      this.displayMonth = new Date(date.getFullYear(), date.getMonth(), 1);
      this.loadEventsForMonth(date.getFullYear(), date.getMonth());
    }
    this.render();
    await this.openDailyNote(date);
  }
  async openDailyNote(date) {
    const { settings, app } = this.plugin;
    const fileName = formatDate(date, settings.dailyNoteFormat) + ".md";
    const folder = settings.dailyNoteFolder.trim().replace(/\/$/, "");
    const filePath = folder ? `${folder}/${fileName}` : fileName;
    const existing = app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian.TFile) {
      const leaf = app.workspace.getLeaf(false);
      await leaf.openFile(existing);
      return;
    }
    new ConfirmCreateModal(
      app,
      `There is no daily note for ${date.toDateString()}. Would you like to create one?`,
      async () => {
        try {
          if (folder) {
            const folderExists = app.vault.getAbstractFileByPath(folder);
            if (!folderExists)
              await app.vault.createFolder(folder);
          }
          const newFile = await app.vault.create(filePath, "");
          const leaf = app.workspace.getLeaf(false);
          await leaf.openFile(newFile);
        } catch (e) {
          new import_obsidian.Notice(`Failed to create daily note: ${e instanceof Error ? e.message : String(e)}`);
        }
      }
    ).open();
  }
  async openWeeklyNote(weekYear, weekNum) {
    const { settings, app } = this.plugin;
    const folder = settings.dailyNoteFolder.trim().replace(/\/$/, "");
    const fileName = `${weekYear}-W${pad2(weekNum)}.md`;
    const filePath = folder ? `${folder}/${fileName}` : fileName;
    const existing = app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian.TFile) {
      const leaf = app.workspace.getLeaf(false);
      await leaf.openFile(existing);
      return;
    }
    new ConfirmCreateModal(
      app,
      `There is no weekly note for ${weekYear}-W${pad2(weekNum)}. Would you like to create one?`,
      async () => {
        try {
          if (folder) {
            const folderExists = app.vault.getAbstractFileByPath(folder);
            if (!folderExists)
              await app.vault.createFolder(folder);
          }
          const newFile = await app.vault.create(filePath, "");
          const leaf = app.workspace.getLeaf(false);
          await leaf.openFile(newFile);
        } catch (e) {
          new import_obsidian.Notice(`Failed to create weekly note: ${e instanceof Error ? e.message : String(e)}`);
        }
      }
    ).open();
  }
};
var CalendarSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Calendar with Apple Events \u2014 Settings" });
    const s = this.plugin.settings;
    if (!s.iCloudUsername || !s.iCloudPassword || !s.calendarName) {
      containerEl.createDiv({
        cls: "cal-settings-warning",
        text: "\u26A0 iCloud credentials are not fully configured. Events will not load until all three fields below are filled in."
      });
    }
    containerEl.createEl("h3", { text: "iCloud CalDAV" });
    containerEl.createEl("p", {
      text: "Use your Apple ID email as username. For the password, generate an app-specific password at appleid.apple.com \u2192 Sign-In and Security \u2192 App-Specific Passwords.",
      attr: { style: "font-size:12px;color:var(--text-muted);margin-bottom:12px" }
    });
    new import_obsidian.Setting(containerEl).setName("iCloud username (Apple ID)").setDesc("Your Apple ID email address, e.g. user@icloud.com").addText(
      (t) => t.setPlaceholder("user@icloud.com").setValue(this.plugin.settings.iCloudUsername).onChange(async (v) => {
        this.plugin.settings.iCloudUsername = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("App-specific password").setDesc("Generate at appleid.apple.com. NOT your main Apple ID password.").addText((t) => {
      t.inputEl.type = "password";
      t.setPlaceholder("xxxx-xxxx-xxxx-xxxx").setValue(this.plugin.settings.iCloudPassword).onChange(async (v) => {
        this.plugin.settings.iCloudPassword = v.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Calendar name").setDesc("Exact name of the Apple Calendar to display (case-insensitive).").addText(
      (t) => t.setPlaceholder("Work").setValue(this.plugin.settings.calendarName).onChange(async (v) => {
        this.plugin.settings.calendarName = v.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Daily Notes" });
    new import_obsidian.Setting(containerEl).setName("Daily note format").setDesc("Date format tokens: YYYY (year), MM (month), DD (day). Must match your daily note filenames.").addText(
      (t) => t.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dailyNoteFormat).onChange(async (v) => {
        this.plugin.settings.dailyNoteFormat = v.trim() || "YYYY-MM-DD";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Daily note folder").setDesc("Folder path inside your vault where daily notes live, e.g. 'Journal/Daily'. Leave empty for vault root.").addText(
      (t) => t.setPlaceholder("Journal/Daily").setValue(this.plugin.settings.dailyNoteFolder).onChange(async (v) => {
        this.plugin.settings.dailyNoteFolder = v.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Connection" });
    new import_obsidian.Setting(containerEl).setName("Test iCloud connection").setDesc("Discover the calendar URL and verify credentials are correct.").addButton(
      (btn) => btn.setButtonText("Test connection").onClick(async () => {
        btn.setButtonText("Testing\u2026");
        btn.setDisabled(true);
        try {
          this.plugin.caldav.reset();
          const url = await this.plugin.caldav.discoverCalendarUrl();
          new import_obsidian.Notice(`\u2713 Connected! Calendar URL found:
${url}`, 8e3);
        } catch (e) {
          new import_obsidian.Notice(`\u2717 ${e instanceof Error ? e.message : String(e)}`, 1e4);
        } finally {
          btn.setButtonText("Test connection");
          btn.setDisabled(false);
        }
      })
    );
  }
};
var CalPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
  }
  async onload() {
    await this.loadSettings();
    this.caldav = new CalDAVClient(this.settings);
    this.registerView(VIEW_TYPE, (leaf) => {
      this.view = new CalendarView(leaf, this);
      return this.view;
    });
    this.addRibbonIcon("calendar", "Open Calendar", () => this.activateView());
    this.addCommand({
      id: "open-calendar",
      name: "Open calendar sidebar",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "refresh-calendar",
      name: "Refresh calendar events",
      callback: () => {
        var _a;
        return (_a = this.view) == null ? void 0 : _a.refresh();
      }
    });
    this.addSettingTab(new CalendarSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    this.caldav = new CalDAVClient(this.settings);
    (_a = this.view) == null ? void 0 : _a.refresh();
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      leaf = (_a = workspace.getRightLeaf(false)) != null ? _a : workspace.getLeaf(true);
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
  }
};
