/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CalPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  iCloudUsername: "",
  iCloudPassword: "",
  calendarName: "",
  dailyNoteFormat: "YYYY-MM-DD",
  dailyNoteFolder: ""
};
var VIEW_TYPE = "obsidian-cal-view";
var WEATHER_ICONS = {
  0: "\u2600\uFE0F",
  1: "\u{1F324}",
  2: "\u26C5\uFE0F",
  3: "\u2601\uFE0F",
  45: "\u{1F32B}",
  48: "\u{1F32B}",
  51: "\u2614\uFE0F",
  53: "\u2614\uFE0F",
  55: "\u2614\uFE0F",
  56: "\u2614\uFE0F",
  57: "\u2614\uFE0F",
  61: "\u2614\uFE0F",
  63: "\u2614\uFE0F",
  65: "\u2614\uFE0F",
  66: "\u2614\uFE0F",
  67: "\u2614\uFE0F",
  71: "\u2744\uFE0F",
  73: "\u2744\uFE0F",
  75: "\u2744\uFE0F",
  77: "\u2744\uFE0F",
  80: "\u2614\uFE0F",
  81: "\u2614\uFE0F",
  82: "\u2614\uFE0F",
  85: "\u2744\uFE0F",
  86: "\u2744\uFE0F",
  95: "\u26A1\uFE0F",
  96: "\u26A1\uFE0F",
  99: "\u26A1\uFE0F"
};
var OT_DOW = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
function simpleWeekInfo(sunday) {
  const saturday = new Date(sunday);
  saturday.setDate(sunday.getDate() + 6);
  let year = sunday.getFullYear();
  if (saturday.getMonth() === 0 && saturday.getFullYear() === year + 1) {
    year = year + 1;
  }
  const jan1 = new Date(year, 0, 1);
  const week1Start = new Date(year, 0, 1 - jan1.getDay());
  const diffDays = Math.round((sunday.getTime() - week1Start.getTime()) / 864e5);
  const weekNum = Math.floor(diffDays / 7) + 1;
  return { weekYear: year, weekNum };
}
function formatDate(date, fmt) {
  return fmt.replace("YYYY", String(date.getFullYear())).replace("MM", String(date.getMonth() + 1).padStart(2, "0")).replace("DD", String(date.getDate()).padStart(2, "0"));
}
function pad2(n) {
  return String(n).padStart(2, "0");
}
function formatTime(date) {
  return `${pad2(date.getHours())}:${pad2(date.getMinutes())}`;
}
function formatEventDate(date) {
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const yyyy = String(date.getFullYear()).slice(-4);
  return `${months[date.getMonth()]} ${date.getDate()}, ${yyyy}`;
}
var DAY_NAMES = ["SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY"];
var DOW_LABELS = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];
function sameDay(a, b) {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}
function adjustFileName(day, name) {
  return day + "_" + name.replace(/: /g, "_").replace(/:/g, "-").replace(/：/g, "_").replace(/\//g, "-").replace(/ /g, "-");
}
function formatHHMM(hhmm) {
  return `${hhmm.slice(0, 2)}:${hhmm.slice(2, 4)}`;
}
function isoDate(date) {
  return formatDate(date, "YYYY-MM-DD");
}
function dateFromIso(dateStr) {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(dateStr);
  if (!match)
    return null;
  const date = new Date(Number(match[1]), Number(match[2]) - 1, Number(match[3]), 12);
  return isoDate(date) === dateStr ? date : null;
}
function dowFor(dateStr) {
  const date = new Date(`${dateStr}T12:00:00Z`);
  return OT_DOW[(date.getUTCDay() + 6) % 7];
}
function errorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}
function toCalDAVDate(date) {
  return `${date.getUTCFullYear()}${pad2(date.getUTCMonth() + 1)}${pad2(date.getUTCDate())}T000000Z`;
}
function unescapeICalText(s) {
  return s.replace(/\\,/g, ",").replace(/\\;/g, ";").replace(/\\n/g, "\n").replace(/\\\\/g, "\\");
}
function parseICalDate(value, params) {
  const isAllDay = params.includes("VALUE=DATE") || /^\d{8}$/.test(value);
  if (isAllDay) {
    const yr2 = parseInt(value.slice(0, 4));
    const mo2 = parseInt(value.slice(4, 6)) - 1;
    const dy2 = parseInt(value.slice(6, 8));
    return { date: new Date(yr2, mo2, dy2, 0, 0, 0), isAllDay: true };
  }
  if (value.endsWith("Z")) {
    const yr2 = parseInt(value.slice(0, 4));
    const mo2 = parseInt(value.slice(4, 6)) - 1;
    const dy2 = parseInt(value.slice(6, 8));
    const hr2 = parseInt(value.slice(9, 11));
    const mn2 = parseInt(value.slice(11, 13));
    const sc2 = parseInt(value.slice(13, 15));
    return { date: new Date(Date.UTC(yr2, mo2, dy2, hr2, mn2, sc2)), isAllDay: false };
  }
  const yr = parseInt(value.slice(0, 4));
  const mo = parseInt(value.slice(4, 6)) - 1;
  const dy = parseInt(value.slice(6, 8));
  const hr = parseInt(value.slice(9, 11));
  const mn = parseInt(value.slice(11, 13));
  const sc = parseInt(value.slice(13, 15));
  return { date: new Date(yr, mo, dy, hr, mn, sc), isAllDay: false };
}
function parseICalEvents(icalText) {
  var _a, _b, _c, _d;
  const unfolded = icalText.replace(/\r\n/g, "\n").replace(/\n[ \t]/g, "");
  const lines = unfolded.split("\n");
  const events = [];
  let inEvent = false;
  let cur = { categories: [] };
  for (const raw of lines) {
    const line = raw.trim();
    if (line === "BEGIN:VEVENT") {
      inEvent = true;
      cur = { categories: [], hasAlarm: false };
      continue;
    }
    if (line === "END:VEVENT") {
      if (cur.summary && cur.start) {
        events.push({
          uid: (_a = cur.uid) != null ? _a : "",
          summary: cur.summary,
          start: cur.start,
          end: (_b = cur.end) != null ? _b : cur.start,
          isAllDay: (_c = cur.isAllDay) != null ? _c : false,
          hasAlarm: (_d = cur.hasAlarm) != null ? _d : false,
          categories: cur.categories
        });
      }
      inEvent = false;
      cur = { categories: [] };
      continue;
    }
    if (!inEvent)
      continue;
    if (line === "BEGIN:VALARM") {
      cur.hasAlarm = true;
      continue;
    }
    const colonIdx = line.indexOf(":");
    if (colonIdx < 0)
      continue;
    const propFull = line.slice(0, colonIdx);
    const value = line.slice(colonIdx + 1);
    const semiIdx = propFull.indexOf(";");
    const propName = semiIdx >= 0 ? propFull.slice(0, semiIdx) : propFull;
    const params = semiIdx >= 0 ? propFull.slice(semiIdx + 1) : "";
    switch (propName) {
      case "UID":
        cur.uid = value;
        break;
      case "SUMMARY":
        cur.summary = unescapeICalText(value);
        break;
      case "CATEGORIES":
        cur.categories = value.split(",").map((c) => c.trim()).filter(Boolean);
        break;
      case "DTSTART": {
        const p = parseICalDate(value, params);
        cur.start = p.date;
        cur.isAllDay = p.isAllDay;
        break;
      }
      case "DTEND": {
        cur.end = parseICalDate(value, params).date;
        break;
      }
    }
  }
  return events;
}
function unfoldICalLines(text) {
  return text.replace(/\r?\n[ \t]/g, "");
}
function getICalProp(lines, key) {
  const re = new RegExp(`^${key}(?:;[^:]*)?:(.+)$`, "i");
  for (const line of lines) {
    const match = line.match(re);
    if (match)
      return { value: match[1].trim(), rawLine: line };
  }
  return null;
}
function getICalTzid(rawLine) {
  const match = rawLine.match(/TZID=([^;:]+)/i);
  return match ? match[1] : null;
}
function normalizeTimeZone(timeZone) {
  return timeZone.replace(/%2F/gi, "/");
}
function localToUtcMs(localStr, timeZone) {
  const naiveUtc = new Date(`${localStr}Z`).getTime();
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false
  }).formatToParts(new Date(naiveUtc));
  const get = (type) => {
    var _a, _b;
    return (_b = (_a = parts.find((part) => part.type === type)) == null ? void 0 : _a.value) != null ? _b : "00";
  };
  const localFromUtc = new Date(
    `${get("year")}-${get("month")}-${get("day")}T${get("hour").replace("24", "00")}:${get("minute")}:${get("second")}Z`
  ).getTime();
  return naiveUtc + (naiveUtc - localFromUtc);
}
function parseOTICalDate(value, tzid, targetTz) {
  if (/^\d{8}$/.test(value)) {
    return {
      dateStr: `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}`,
      timeStr: null,
      isDate: true
    };
  }
  const localStr = `${value.slice(0, 4)}-${value.slice(4, 6)}-${value.slice(6, 8)}T${value.slice(9, 11)}:${value.slice(11, 13)}:${value.slice(13, 15)}`;
  const normalizedTargetTz = normalizeTimeZone(targetTz);
  const utcMs = value.endsWith("Z") ? new Date(`${localStr}Z`).getTime() : localToUtcMs(localStr, normalizeTimeZone(tzid != null ? tzid : targetTz));
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: normalizedTargetTz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false
  }).formatToParts(new Date(utcMs));
  const get = (type) => {
    var _a, _b;
    return (_b = (_a = parts.find((part) => part.type === type)) == null ? void 0 : _a.value) != null ? _b : "00";
  };
  return {
    dateStr: `${get("year")}-${get("month")}-${get("day")}`,
    timeStr: `${get("hour").replace("24", "00").padStart(2, "0")}${get("minute").padStart(2, "0")}`,
    isDate: false
  };
}
function parseOTICalEvents(icalText, targetTz) {
  const events = [];
  const blocks = icalText.split(/BEGIN:VEVENT/i).slice(1);
  for (const block of blocks) {
    const lines = unfoldICalLines(block).split(/\r?\n/).filter(Boolean);
    const summaryProp = getICalProp(lines, "SUMMARY");
    const startProp = getICalProp(lines, "DTSTART");
    const endProp = getICalProp(lines, "DTEND");
    const locationProp = getICalProp(lines, "LOCATION");
    const descriptionProp = getICalProp(lines, "DESCRIPTION");
    if (!summaryProp || !startProp)
      continue;
    const start = parseOTICalDate(startProp.value, getICalTzid(startProp.rawLine), targetTz);
    const end = endProp ? parseOTICalDate(endProp.value, getICalTzid(endProp.rawLine), targetTz) : start;
    events.push({
      summary: unescapeICalText(summaryProp.value),
      start,
      end,
      location: locationProp ? unescapeICalText(locationProp.value) : "",
      description: descriptionProp ? unescapeICalText(descriptionProp.value) : ""
    });
  }
  return events;
}
var OTEvent = class {
  constructor(raw) {
    this.validEvent = true;
    this.mtgNote = true;
    this.tags = "";
    this.participants = "";
    var _a, _b;
    this.name = raw.summary;
    if (/^\(.*\)$/.test(this.name)) {
      this.validEvent = false;
      this.mtgNote = false;
      this.name = this.name.slice(1, -1);
    } else if (/^\[.*\]$/.test(this.name)) {
      this.name = this.name.slice(1, -1);
    } else if (/^<.*>$/.test(this.name)) {
      this.mtgNote = false;
      this.name = this.name.slice(1, -1);
    }
    if (raw.start.isDate) {
      this.validEvent = false;
      this.mtgNote = false;
    }
    this.day = raw.start.dateStr;
    this.timeStart = (_a = raw.start.timeStr) != null ? _a : "0000";
    this.timeEnd = (_b = raw.end.timeStr) != null ? _b : "0000";
    this.location = raw.location;
    for (const line of raw.description.split("\n")) {
      if (/^#\S+/.test(line.trim())) {
        this.tags += `${line.trim().replace(/#/g, "")} `;
      } else if (line.trim()) {
        this.participants += `${line}
`;
      }
    }
    this.participants = this.participants.trimEnd();
    this.tags = this.tags.trim();
  }
  formatEvent() {
    const range = `- ${formatHHMM(this.timeStart)}-${formatHHMM(this.timeEnd)}`;
    if (!this.mtgNote)
      return `${range} ${this.name}`;
    const fileName = adjustFileName(this.day, this.name);
    return `${range} [[${fileName}|${this.day} ${this.name}]]`;
  }
  buildMtgNote(template) {
    return template.replace(/\{\{date:YYYY-MM-DD\}\}/g, this.day).replace(/\{\{title\}\}/g, this.name).replace(
      /\{\{date:\[\[\[\]YYYY-MM-DD\[\]\]\] \[\(\]ddd\[\)\] HH:mm\}\}/g,
      `[[${this.day}]] (${dowFor(this.day)}) ${formatHHMM(this.timeStart)}-${formatHHMM(this.timeEnd)}`
    ).replace(/\{\{location\}\}/g, this.location).replace(/\{\{participants\}\}/g, this.participants).replace(/\{\{tags\}\}/g, this.tags);
  }
};
var CalDAVClient = class {
  constructor(settings) {
    this.baseUrl = "https://caldav.icloud.com";
    this.calendarUrl = null;
    this.settings = settings;
  }
  authHeader() {
    return "Basic " + btoa(`${this.settings.iCloudUsername}:${this.settings.iCloudPassword}`);
  }
  resolveUrl(href) {
    if (href.startsWith("http://") || href.startsWith("https://"))
      return href;
    if (href.startsWith("/")) {
      const u = new URL(this.baseUrl);
      return `${u.protocol}//${u.host}${href}`;
    }
    return `${this.baseUrl.replace(/\/$/, "")}/${href}`;
  }
  // Extract text from the first XML element matching localName (namespace-agnostic)
  xmlText(xmlText, localName) {
    const re = new RegExp(`<[^>]*:?${localName}[^>]*>([\\s\\S]*?)<\\/[^>]*:?${localName}>`, "i");
    const m = xmlText.match(re);
    return m ? m[1].trim() : null;
  }
  // Extract all <href> values inside each <response>
  xmlAllHrefs(xml) {
    const results = [];
    const responseRe = /<[^>]*:?response[^>]*>([\s\S]*?)<\/[^>]*:?response>/gi;
    let m;
    while ((m = responseRe.exec(xml)) !== null) {
      const block = m[1];
      const hrefMatch = block.match(/<[^>]*:?href[^>]*>([\s\S]*?)<\/[^>]*:?href>/i);
      const nameMatch = block.match(/<[^>]*:?displayname[^>]*>([\s\S]*?)<\/[^>]*:?displayname>/i);
      if (hrefMatch) {
        results.push({
          href: hrefMatch[1].trim(),
          displayName: nameMatch ? nameMatch[1].trim() : ""
        });
      }
    }
    return results;
  }
  // Extract all calendar-data blocks from a REPORT response
  xmlCalendarData(xml) {
    const data = [];
    const re = /<[^>]*:?calendar-data[^>]*>([\s\S]*?)<\/[^>]*:?calendar-data>/gi;
    let m;
    while ((m = re.exec(xml)) !== null) {
      const raw = m[1].replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&").replace(/&quot;/g, '"');
      data.push(raw);
    }
    return data;
  }
  async discoverCalendarUrl() {
    var _a, _b, _c, _d, _e, _f, _g;
    const resp1 = await (0, import_obsidian.requestUrl)({
      url: `${this.baseUrl}/`,
      method: "PROPFIND",
      headers: {
        Authorization: this.authHeader(),
        Depth: "0",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<d:propfind xmlns:d="DAV:">
  <d:prop><d:current-user-principal/></d:prop>
</d:propfind>`
    });
    const principalHref = (_d = (_c = (_b = (_a = this.xmlText(resp1.text, "current-user-principal")) == null ? void 0 : _a.match(/<[^>]*:?href[^>]*>([\s\S]*?)<\/[^>]*:?href>/i)) == null ? void 0 : _b[1]) == null ? void 0 : _c.trim()) != null ? _d : this.xmlText(resp1.text, "href");
    if (!principalHref)
      throw new Error("Could not find iCloud user principal. Check username/password.");
    const resp2 = await (0, import_obsidian.requestUrl)({
      url: this.resolveUrl(principalHref),
      method: "PROPFIND",
      headers: {
        Authorization: this.authHeader(),
        Depth: "0",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
  <d:prop><c:calendar-home-set/></d:prop>
</d:propfind>`
    });
    const homeHref = (_g = (_f = (_e = this.xmlText(resp2.text, "calendar-home-set")) == null ? void 0 : _e.match(/<[^>]*:?href[^>]*>([\s\S]*?)<\/[^>]*:?href>/i)) == null ? void 0 : _f[1]) == null ? void 0 : _g.trim();
    if (!homeHref)
      throw new Error("Could not find iCloud calendar home. Check credentials.");
    const resp3 = await (0, import_obsidian.requestUrl)({
      url: this.resolveUrl(homeHref),
      method: "PROPFIND",
      headers: {
        Authorization: this.authHeader(),
        Depth: "1",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<d:propfind xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">
  <d:prop>
    <d:displayname/>
    <d:resourcetype/>
  </d:prop>
</d:propfind>`
    });
    const calendars = this.xmlAllHrefs(resp3.text);
    const target = this.settings.calendarName.toLowerCase().trim();
    const found = calendars.find((c) => c.displayName.toLowerCase().trim() === target);
    if (!found) {
      const names = calendars.map((c) => `"${c.displayName}"`).join(", ");
      throw new Error(
        `Calendar "${this.settings.calendarName}" not found.
Available: ${names || "(none)"}`
      );
    }
    return this.resolveUrl(found.href);
  }
  async fetchEvents(year, month) {
    if (!this.calendarUrl) {
      this.calendarUrl = await this.discoverCalendarUrl();
    }
    const firstOfMonth = new Date(year, month, 1);
    const lastOfMonth = new Date(year, month + 1, 0);
    const gridStart = new Date(firstOfMonth);
    gridStart.setDate(gridStart.getDate() - gridStart.getDay());
    const gridEnd = new Date(lastOfMonth);
    gridEnd.setDate(gridEnd.getDate() + (6 - gridEnd.getDay()) + 1);
    const startStr = toCalDAVDate(gridStart);
    const endStr = toCalDAVDate(gridEnd);
    const resp = await (0, import_obsidian.requestUrl)({
      url: this.calendarUrl,
      method: "REPORT",
      headers: {
        Authorization: this.authHeader(),
        Depth: "1",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <D:getetag/>
    <C:calendar-data/>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range start="${startStr}" end="${endStr}"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>`
    });
    const icalBlocks = this.xmlCalendarData(resp.text);
    const events = [];
    for (const block of icalBlocks) {
      events.push(...parseICalEvents(block));
    }
    return events;
  }
  async fetchEventsForDate(dateStr, targetTz) {
    if (!this.settings.iCloudUsername || !this.settings.iCloudPassword || !this.settings.calendarName) {
      throw new Error("iCloud credentials are not configured \u2014 open Settings \u2192 Obsidian Calendar.");
    }
    if (!this.calendarUrl) {
      this.calendarUrl = await this.discoverCalendarUrl();
    }
    const start = new Date(`${dateStr}T00:00:00Z`);
    start.setUTCDate(start.getUTCDate() - 1);
    const end = new Date(`${dateStr}T00:00:00Z`);
    end.setUTCDate(end.getUTCDate() + 2);
    const formatRangeDate = (date) => date.toISOString().replace(/[-:]/g, "").slice(0, 15) + "Z";
    const startStr = formatRangeDate(start);
    const endStr = formatRangeDate(end);
    const response = await (0, import_obsidian.requestUrl)({
      url: this.calendarUrl,
      method: "REPORT",
      headers: {
        Authorization: this.authHeader(),
        Depth: "1",
        "Content-Type": "application/xml; charset=utf-8"
      },
      body: `<?xml version="1.0" encoding="utf-8"?>
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <D:getetag/>
    <C:calendar-data>
      <C:expand start="${startStr}" end="${endStr}"/>
    </C:calendar-data>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range start="${startStr}" end="${endStr}"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>`
    });
    return this.xmlCalendarData(response.text).flatMap((block) => parseOTICalEvents(block, targetTz)).filter((event) => event.start.dateStr === dateStr).sort((a, b) => {
      var _a, _b;
      return ((_a = a.start.timeStr) != null ? _a : "").localeCompare((_b = b.start.timeStr) != null ? _b : "");
    }).map((event) => new OTEvent(event));
  }
  // Call this when settings change so we re-discover on next fetch
  reset() {
    this.calendarUrl = null;
  }
};
var ConfirmCreateModal = class extends import_obsidian.Modal {
  constructor(app, message, onConfirm) {
    super(app);
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "Note not found" });
    contentEl.createEl("p", { text: this.message });
    const btnRow = contentEl.createDiv({ cls: "modal-button-container" });
    const yes = btnRow.createEl("button", { text: "Create", cls: "mod-cta" });
    yes.onclick = () => {
      this.close();
      this.onConfirm();
    };
    const no = btnRow.createEl("button", { text: "Cancel" });
    no.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CreateDailyModal = class extends import_obsidian.Modal {
  constructor(app, plugin, date = new Date()) {
    super(app);
    this.placeKey = null;
    this.overwrite = false;
    this.geo = null;
    this.running = false;
    this.plugin = plugin;
    this.dateStr = isoDate(date);
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Create Daily Note from Calendar" });
    try {
      this.geo = await this.plugin.loadGeoData();
      this.placeKey = this.geo.default;
    } catch (error) {
      contentEl.createEl("p", { text: `Error: ${errorMessage(error)}` });
      return;
    }
    new import_obsidian.Setting(contentEl).setName("Date").addText((text) => text.setValue(this.dateStr).onChange((value) => this.dateStr = value.trim()));
    new import_obsidian.Setting(contentEl).setName("Location").addDropdown((dropdown) => {
      var _a;
      for (const [key, location] of Object.entries(this.geo.location)) {
        dropdown.addOption(key, location.name);
      }
      dropdown.setValue((_a = this.placeKey) != null ? _a : "").onChange((value) => this.placeKey = value);
    });
    new import_obsidian.Setting(contentEl).setName("Overwrite existing files").addToggle((toggle) => toggle.setValue(this.overwrite).onChange((value) => this.overwrite = value));
    this.statusEl = contentEl.createEl("p", { cls: "ot-status" });
    new import_obsidian.Setting(contentEl).addButton((button) => button.setButtonText("Create").setCta().onClick(() => this.run())).addButton((button) => button.setButtonText("Cancel").onClick(() => this.close()));
  }
  async run() {
    if (this.running || !this.geo || !this.placeKey)
      return;
    const date = dateFromIso(this.dateStr);
    if (!date) {
      this.statusEl.setText("Error: Date must be a valid YYYY-MM-DD value.");
      return;
    }
    this.running = true;
    this.statusEl.setText("Fetching calendar events\u2026");
    try {
      if (this.placeKey !== this.geo.default) {
        this.geo.default = this.placeKey;
        await this.plugin.saveGeoData(this.geo);
      }
      const place = this.geo.location[this.placeKey];
      if (!place)
        throw new Error("The selected location is not configured.");
      const events = await this.plugin.fetchOTEvents(this.dateStr, place);
      this.statusEl.setText(`Found ${events.length} event(s). Fetching weather\u2026`);
      const weather = await this.plugin.getWeather(this.dateStr, place);
      this.statusEl.setText("Creating files\u2026");
      let morning = "";
      let lunch = "";
      let afternoon = "";
      let evening = "";
      for (const event of events) {
        if (!event.validEvent)
          continue;
        const time = parseInt(event.timeStart, 10);
        const line = `
${event.formatEvent()}`;
        if (time < 1200)
          morning += line;
        else if (time < 1300)
          lunch += line;
        else if (time < 1700)
          afternoon += line;
        else
          evening += line;
      }
      let body = await this.plugin.readTemplate("daily_template.md");
      body = body.replace(/%WEATHER%/g, weather).replace(/%MORNING%/g, morning).replace(/%LUNCH%/g, lunch).replace(/%AFTERNOON%/g, afternoon).replace(/%EVENING%/g, evening);
      const dailyPath = this.plugin.dailyNotePath(date);
      const dailyResult = await this.plugin.writeFile(dailyPath, body, this.overwrite);
      const meetingEvents = events.filter((event) => event.mtgNote);
      let created = 0;
      let skipped = 0;
      if (meetingEvents.length > 0) {
        const meetingTemplate = await this.plugin.readTemplate("meeting_template.md");
        for (const event of meetingEvents) {
          const path = `${adjustFileName(event.day, event.name)}.md`;
          const content = event.buildMtgNote(meetingTemplate);
          const result = await this.plugin.writeFile(path, content, this.overwrite);
          result === "skipped" ? skipped++ : created++;
        }
      }
      const summary = `Daily note: ${dailyResult}. Meeting notes: ${created} created, ${skipped} skipped.`;
      this.statusEl.setText(summary);
      new import_obsidian.Notice(`Calendar: ${summary}`);
      await this.plugin.openFile(dailyPath);
      window.setTimeout(() => this.close(), 2e3);
    } catch (error) {
      this.statusEl.setText(`Error: ${errorMessage(error)}`);
      console.error("Obsidian Calendar note creation error:", error);
    } finally {
      this.running = false;
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SelectEventModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.dateStr = isoDate(new Date());
    this.placeKey = null;
    this.overwrite = false;
    this.geo = null;
    this.plugin = plugin;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Create Meeting Note \u2014 Select Event" });
    try {
      this.geo = await this.plugin.loadGeoData();
      this.placeKey = this.geo.default;
    } catch (error) {
      contentEl.createEl("p", { text: `Error: ${errorMessage(error)}` });
      return;
    }
    new import_obsidian.Setting(contentEl).setName("Date").addText((text) => text.setValue(this.dateStr).onChange((value) => this.dateStr = value.trim()));
    new import_obsidian.Setting(contentEl).setName("Location").addDropdown((dropdown) => {
      var _a;
      for (const [key, location] of Object.entries(this.geo.location)) {
        dropdown.addOption(key, location.name);
      }
      dropdown.setValue((_a = this.placeKey) != null ? _a : "").onChange((value) => this.placeKey = value);
    });
    new import_obsidian.Setting(contentEl).setName("Overwrite existing files").addToggle((toggle) => toggle.setValue(this.overwrite).onChange((value) => this.overwrite = value));
    this.statusEl = contentEl.createEl("p", { cls: "ot-status" });
    this.listEl = contentEl.createDiv();
    new import_obsidian.Setting(contentEl).addButton((button) => button.setButtonText("Fetch Events").setCta().onClick(() => this.fetchAndShow())).addButton((button) => button.setButtonText("Cancel").onClick(() => this.close()));
  }
  async fetchAndShow() {
    this.statusEl.setText("Fetching events\u2026");
    this.listEl.empty();
    try {
      if (!dateFromIso(this.dateStr))
        throw new Error("Date must be a valid YYYY-MM-DD value.");
      if (!this.geo || !this.placeKey)
        throw new Error("Select a location.");
      const place = this.geo.location[this.placeKey];
      if (!place)
        throw new Error("The selected location is not configured.");
      const events = (await this.plugin.fetchOTEvents(this.dateStr, place)).filter((event) => event.validEvent);
      if (events.length === 0) {
        this.statusEl.setText("No valid events found.");
        return;
      }
      this.statusEl.setText("Click a button to create that meeting note:");
      for (const event of events) {
        new import_obsidian.Setting(this.listEl).setName(`${formatHHMM(event.timeStart)}\u2013${formatHHMM(event.timeEnd)}  ${event.name}`).addButton((button) => button.setButtonText(event.mtgNote ? "Create Note" : "(no note)").setDisabled(!event.mtgNote).onClick(async () => {
          try {
            const template = await this.plugin.readTemplate("meeting_template.md");
            const path = `${adjustFileName(event.day, event.name)}.md`;
            const result = await this.plugin.writeFile(path, event.buildMtgNote(template), this.overwrite);
            new import_obsidian.Notice(`Calendar: ${path} \u2014 ${result}`);
            this.statusEl.setText(`${path} \u2014 ${result}`);
          } catch (error) {
            this.statusEl.setText(`Error: ${errorMessage(error)}`);
          }
        }));
      }
    } catch (error) {
      this.statusEl.setText(`Error: ${errorMessage(error)}`);
      console.error("Obsidian Calendar meeting-note error:", error);
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CalendarView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.eventCache = /* @__PURE__ */ new Map();
    // "YYYY-M" → events
    this.isLoading = false;
    this.lastError = "";
    this.viewMode = "month";
    this.plugin = plugin;
    const now = new Date();
    this.selectedDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    this.displayMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Calendar";
  }
  getIcon() {
    return "calendar";
  }
  async onOpen() {
    this.containerEl.addClass("cal-root");
    await this.render();
    this.loadEventsForMonth(this.displayMonth.getFullYear(), this.displayMonth.getMonth());
  }
  onClose() {
    return Promise.resolve();
  }
  // Public: force refresh (called after settings change)
  async refresh() {
    this.eventCache.clear();
    await this.render();
    this.loadEventsForMonth(this.displayMonth.getFullYear(), this.displayMonth.getMonth());
  }
  cacheKey(year, month) {
    return `${year}-${month}`;
  }
  async loadEventsForMonth(year, month) {
    const s = this.plugin.settings;
    if (!s.iCloudUsername || !s.iCloudPassword || !s.calendarName)
      return;
    const key = this.cacheKey(year, month);
    if (this.eventCache.has(key))
      return;
    this.isLoading = true;
    this.lastError = "";
    this.render();
    try {
      const events = await this.plugin.caldav.fetchEvents(year, month);
      this.eventCache.set(key, events);
      this.lastError = "";
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      this.lastError = msg;
      new import_obsidian.Notice(`Calendar: ${msg}`, 8e3);
    } finally {
      this.isLoading = false;
      this.render();
    }
  }
  eventsForDate(date) {
    var _a;
    const key = this.cacheKey(date.getFullYear(), date.getMonth());
    const all = (_a = this.eventCache.get(key)) != null ? _a : [];
    return all.filter((e) => {
      if (e.isAllDay)
        return sameDay(e.start, date);
      return sameDay(e.start, date);
    }).sort((a, b) => {
      if (a.isAllDay && !b.isAllDay)
        return -1;
      if (!a.isAllDay && b.isAllDay)
        return 1;
      return a.start.getTime() - b.start.getTime();
    });
  }
  hasEvents(date) {
    const key = this.cacheKey(date.getFullYear(), date.getMonth());
    if (!this.eventCache.has(key))
      return false;
    return this.eventsForDate(date).length > 0;
  }
  async render() {
    const { contentEl } = this;
    contentEl.empty();
    const container = contentEl.createDiv({ cls: "cal-container" });
    this.renderHeader(container);
    if (this.viewMode === "week") {
      this.renderWeekGrid(container);
    } else {
      this.renderGrid(container);
    }
    container.createDiv({ cls: "cal-separator" });
    await this.renderEventSection(container);
  }
  // ---- Header ----
  renderHeader(parent) {
    const header = parent.createDiv({ cls: "cal-header" });
    if (this.viewMode === "week") {
      const sunday = new Date(this.selectedDate);
      sunday.setDate(sunday.getDate() - sunday.getDay());
      const { weekYear, weekNum } = simpleWeekInfo(sunday);
      header.createDiv({ cls: "cal-title", text: `${weekYear}-W${pad2(weekNum)}` });
      const nav = header.createDiv({ cls: "cal-nav" });
      const prev = nav.createEl("button", { cls: "cal-nav-btn", text: "\u2039" });
      prev.title = "Previous week";
      prev.onclick = () => this.navigateWeek(-1);
      const next = nav.createEl("button", { cls: "cal-nav-btn", text: "\u203A" });
      next.title = "Next week";
      next.onclick = () => this.navigateWeek(1);
    } else {
      const yr = this.displayMonth.getFullYear();
      const mo = this.displayMonth.getMonth();
      header.createDiv({ cls: "cal-title", text: `${yr}-${pad2(mo + 1)}` });
      const nav = header.createDiv({ cls: "cal-nav" });
      const prev = nav.createEl("button", { cls: "cal-nav-btn", text: "\u2039" });
      prev.title = "Previous month";
      prev.onclick = () => this.navigateMonth(-1);
      const next = nav.createEl("button", { cls: "cal-nav-btn", text: "\u203A" });
      next.title = "Next month";
      next.onclick = () => this.navigateMonth(1);
    }
  }
  navigateMonth(delta) {
    const d = this.displayMonth;
    this.displayMonth = new Date(d.getFullYear(), d.getMonth() + delta, 1);
    this.render();
    this.loadEventsForMonth(this.displayMonth.getFullYear(), this.displayMonth.getMonth());
  }
  navigateWeek(delta) {
    const d = new Date(this.selectedDate);
    d.setDate(d.getDate() + delta * 7);
    this.selectedDate = d;
    this.displayMonth = new Date(d.getFullYear(), d.getMonth(), 1);
    this.render();
    this.loadEventsForMonth(d.getFullYear(), d.getMonth());
  }
  // ---- Calendar grid ----
  renderGrid(parent) {
    var _a;
    const grid = parent.createDiv({ cls: "cal-grid" });
    grid.createDiv({ cls: "cal-grid-header-cw", text: "W" });
    DOW_LABELS.forEach((label, i) => {
      const el = grid.createDiv({ cls: "cal-dow-label" + (i === 0 ? " cal-sunday" : "") });
      el.setText(label);
    });
    const today = new Date();
    const year = this.displayMonth.getFullYear();
    const month = this.displayMonth.getMonth();
    const gridStart = new Date(year, month, 1);
    gridStart.setDate(gridStart.getDate() - gridStart.getDay());
    const lastOfMonth = new Date(year, month + 1, 0);
    for (let week = 0; week < 6; week++) {
      const sunday = new Date(gridStart);
      sunday.setDate(gridStart.getDate() + week * 7);
      if (week > 0 && sunday > lastOfMonth)
        break;
      const { weekYear, weekNum } = simpleWeekInfo(sunday);
      const wnCell = grid.createDiv({ cls: "cal-week-num", text: String(weekNum) });
      wnCell.title = `Open weekly note ${weekYear}-W${pad2(weekNum)}`;
      wnCell.onclick = () => this.openWeeklyNote(weekYear, weekNum);
      for (let dow = 0; dow < 7; dow++) {
        const cellDate = new Date(sunday);
        cellDate.setDate(sunday.getDate() + dow);
        const isOtherMonth = cellDate.getMonth() !== month;
        const isToday = sameDay(cellDate, today);
        const isSelected = sameDay(cellDate, this.selectedDate);
        const isSunday = dow === 0;
        let cls = "cal-day-cell";
        if (isOtherMonth)
          cls += " cal-other-month";
        if (isToday)
          cls += " cal-today";
        if (isSelected)
          cls += " cal-selected";
        if (isSunday)
          cls += " cal-sunday";
        const cell = grid.createDiv({ cls });
        const numEl = cell.createDiv({ cls: "cal-day-num" });
        numEl.setText(String(cellDate.getDate()));
        const dotsEl = cell.createDiv({ cls: "cal-day-dots" });
        const evs = this.eventsForDate(cellDate);
        const maxDots = 3;
        const dotsCount = Math.min(evs.length, maxDots);
        for (let d = 0; d < dotsCount; d++) {
          const dot = dotsEl.createDiv({ cls: "cal-dot" });
          if ((_a = evs[d]) == null ? void 0 : _a.isAllDay)
            dot.addClass("cal-allday");
        }
        const dateCopy = new Date(cellDate);
        cell.onclick = () => this.selectDate(dateCopy);
      }
    }
  }
  // ---- Weekly grid (single row) ----
  renderWeekGrid(parent) {
    var _a;
    const grid = parent.createDiv({ cls: "cal-grid" });
    grid.createDiv({ cls: "cal-grid-header-cw", text: "W" });
    DOW_LABELS.forEach((label, i) => {
      const el = grid.createDiv({ cls: "cal-dow-label" + (i === 0 ? " cal-sunday" : "") });
      el.setText(label);
    });
    const today = new Date();
    const sunday = new Date(this.selectedDate);
    sunday.setDate(sunday.getDate() - sunday.getDay());
    const { weekYear, weekNum } = simpleWeekInfo(sunday);
    const wnCell = grid.createDiv({ cls: "cal-week-num", text: String(weekNum) });
    wnCell.title = `Open weekly note ${weekYear}-W${pad2(weekNum)}`;
    wnCell.onclick = () => this.openWeeklyNote(weekYear, weekNum);
    for (let dow = 0; dow < 7; dow++) {
      const cellDate = new Date(sunday);
      cellDate.setDate(sunday.getDate() + dow);
      const isToday = sameDay(cellDate, today);
      const isSelected = sameDay(cellDate, this.selectedDate);
      const isSunday = dow === 0;
      let cls = "cal-day-cell";
      if (isToday)
        cls += " cal-today";
      if (isSelected)
        cls += " cal-selected";
      if (isSunday)
        cls += " cal-sunday";
      const cell = grid.createDiv({ cls });
      const numEl = cell.createDiv({ cls: "cal-day-num" });
      numEl.setText(String(cellDate.getDate()));
      const dotsEl = cell.createDiv({ cls: "cal-day-dots" });
      const evs = this.eventsForDate(cellDate);
      const dotsCount = Math.min(evs.length, 3);
      for (let d = 0; d < dotsCount; d++) {
        const dot = dotsEl.createDiv({ cls: "cal-dot" });
        if ((_a = evs[d]) == null ? void 0 : _a.isAllDay)
          dot.addClass("cal-allday");
      }
      const dateCopy = new Date(cellDate);
      cell.onclick = () => this.selectDate(dateCopy);
    }
  }
  // ---- Event section ----
  async renderEventSection(parent) {
    var _a;
    const section = parent.createDiv({ cls: "cal-event-section" });
    const sectionHeader = section.createDiv({ cls: "cal-event-section-header" });
    const viewToggleBtn = sectionHeader.createEl("button", { cls: "cal-view-toggle-btn" });
    viewToggleBtn.setText(this.viewMode === "month" ? "W" : "M");
    viewToggleBtn.title = this.viewMode === "month" ? "Switch to weekly view" : "Switch to monthly view";
    viewToggleBtn.onclick = (e) => {
      e.stopPropagation();
      this.viewMode = this.viewMode === "month" ? "week" : "month";
      this.render();
    };
    const refreshBtn = sectionHeader.createEl("button", { cls: "cal-refresh-btn", text: "\u21BB" });
    refreshBtn.title = "Refresh events";
    refreshBtn.onclick = (e) => {
      e.stopPropagation();
      this.refresh();
    };
    const listEl = section.createDiv({ cls: "cal-event-list" });
    const dayHeader = listEl.createDiv({ cls: "cal-event-day-header" });
    dayHeader.createSpan({
      cls: "cal-event-day-name",
      text: DAY_NAMES[this.selectedDate.getDay()]
    });
    dayHeader.createSpan({
      cls: "cal-event-date-label",
      text: formatEventDate(this.selectedDate)
    });
    const s = this.plugin.settings;
    if (!s.iCloudUsername || !s.iCloudPassword || !s.calendarName) {
      const status = listEl.createDiv({ cls: "cal-status" });
      status.setText("Configure iCloud credentials in Settings to see events.");
      return;
    }
    if (this.isLoading) {
      listEl.createDiv({ cls: "cal-status", text: "Loading events\u2026" });
      return;
    }
    if (this.lastError) {
      const errEl = listEl.createDiv({ cls: "cal-status cal-error" });
      errEl.setText(`Error: ${this.lastError}`);
      const retryBtn = listEl.createEl("button", { cls: "cal-retry-btn", text: "Retry" });
      retryBtn.onclick = () => {
        this.plugin.caldav.reset();
        this.eventCache.clear();
        this.loadEventsForMonth(this.displayMonth.getFullYear(), this.displayMonth.getMonth());
      };
      return;
    }
    const key = this.cacheKey(this.selectedDate.getFullYear(), this.selectedDate.getMonth());
    if (!this.eventCache.has(key)) {
      listEl.createDiv({ cls: "cal-status", text: "Loading events\u2026" });
      return;
    }
    const events = this.eventsForDate(this.selectedDate);
    const allCats = /* @__PURE__ */ new Set();
    events.forEach((e) => e.categories.forEach((c) => allCats.add(c)));
    if (allCats.size > 0) {
      const tagsEl = listEl.createDiv({ cls: "cal-tags" });
      allCats.forEach((cat) => tagsEl.createSpan({ cls: "cal-tag", text: cat }));
    }
    if (events.length === 0) {
      listEl.createDiv({ cls: "cal-status", text: "No events for this day." });
      return;
    }
    const { app } = this.plugin;
    const folder = this.plugin.settings.dailyNoteFolder.trim().replace(/\/$/, "");
    const dayStr = formatDate(this.selectedDate, "YYYY-MM-DD");
    for (const ev of events) {
      const item = listEl.createDiv({ cls: "cal-event-item" });
      item.createDiv({ cls: "cal-event-bullet" });
      const content = item.createDiv({ cls: "cal-event-content" });
      if (ev.isAllDay) {
        content.createDiv({ cls: "cal-event-allday-label", text: "All day" });
      } else {
        const timeText = `${formatTime(ev.start)} \u2013 ${formatTime(ev.end)}${ev.hasAlarm ? "  \u23F0" : ""}`;
        content.createDiv({ cls: "cal-event-time", text: timeText });
      }
      const noteFileName = adjustFileName(dayStr, ev.summary) + ".md";
      const noteFile = (_a = app.vault.getFiles().find((f) => f.name === noteFileName)) != null ? _a : null;
      if (noteFile instanceof import_obsidian.TFile) {
        const link = content.createEl("a", { cls: "cal-event-title cal-event-title-link", text: ev.summary });
        link.onclick = async (e) => {
          e.preventDefault();
          const leaf = app.workspace.getLeaf(false);
          await leaf.openFile(noteFile);
        };
      } else {
        content.createDiv({ cls: "cal-event-title", text: ev.summary });
      }
    }
  }
  // ---- Select a date & open daily note ----
  async selectDate(date) {
    this.selectedDate = date;
    if (date.getFullYear() !== this.displayMonth.getFullYear() || date.getMonth() !== this.displayMonth.getMonth()) {
      this.displayMonth = new Date(date.getFullYear(), date.getMonth(), 1);
      this.loadEventsForMonth(date.getFullYear(), date.getMonth());
    }
    this.render();
    await this.openDailyNote(date);
  }
  async openDailyNote(date) {
    const { app } = this.plugin;
    const filePath = this.plugin.dailyNotePath(date);
    const existing = app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian.TFile) {
      const leaf = app.workspace.getLeaf(false);
      await leaf.openFile(existing);
      return;
    }
    new CreateDailyModal(app, this.plugin, date).open();
  }
  async openWeeklyNote(weekYear, weekNum) {
    const { settings, app } = this.plugin;
    const folder = settings.dailyNoteFolder.trim().replace(/\/$/, "");
    const fileName = `${weekYear}-W${pad2(weekNum)}.md`;
    const filePath = folder ? `${folder}/${fileName}` : fileName;
    const existing = app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian.TFile) {
      const leaf = app.workspace.getLeaf(false);
      await leaf.openFile(existing);
      return;
    }
    new ConfirmCreateModal(
      app,
      `There is no weekly note for ${weekYear}-W${pad2(weekNum)}. Would you like to create one?`,
      async () => {
        try {
          if (folder) {
            const folderExists = app.vault.getAbstractFileByPath(folder);
            if (!folderExists)
              await app.vault.createFolder(folder);
          }
          const newFile = await app.vault.create(filePath, "");
          const leaf = app.workspace.getLeaf(false);
          await leaf.openFile(newFile);
        } catch (e) {
          new import_obsidian.Notice(`Failed to create weekly note: ${e instanceof Error ? e.message : String(e)}`);
        }
      }
    ).open();
  }
};
var CalendarSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Calendar with Apple Events \u2014 Settings" });
    const s = this.plugin.settings;
    if (!s.iCloudUsername || !s.iCloudPassword || !s.calendarName) {
      containerEl.createDiv({
        cls: "cal-settings-warning",
        text: "\u26A0 iCloud credentials are not fully configured. Events will not load until all three fields below are filled in."
      });
    }
    containerEl.createEl("h3", { text: "iCloud CalDAV" });
    containerEl.createEl("p", {
      text: "Use your Apple ID email as username. For the password, generate an app-specific password at appleid.apple.com \u2192 Sign-In and Security \u2192 App-Specific Passwords.",
      attr: { style: "font-size:12px;color:var(--text-muted);margin-bottom:12px" }
    });
    new import_obsidian.Setting(containerEl).setName("iCloud username (Apple ID)").setDesc("Your Apple ID email address, e.g. user@icloud.com").addText(
      (t) => t.setPlaceholder("user@icloud.com").setValue(this.plugin.settings.iCloudUsername).onChange(async (v) => {
        this.plugin.settings.iCloudUsername = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("App-specific password").setDesc("Generate at appleid.apple.com. NOT your main Apple ID password.").addText((t) => {
      t.inputEl.type = "password";
      t.setPlaceholder("xxxx-xxxx-xxxx-xxxx").setValue(this.plugin.settings.iCloudPassword).onChange(async (v) => {
        this.plugin.settings.iCloudPassword = v.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Calendar name").setDesc("Exact name of the Apple Calendar to display (case-insensitive).").addText(
      (t) => t.setPlaceholder("Work").setValue(this.plugin.settings.calendarName).onChange(async (v) => {
        this.plugin.settings.calendarName = v.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Daily Notes" });
    new import_obsidian.Setting(containerEl).setName("Daily note format").setDesc("Date format tokens: YYYY (year), MM (month), DD (day). Must match your daily note filenames.").addText(
      (t) => t.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dailyNoteFormat).onChange(async (v) => {
        this.plugin.settings.dailyNoteFormat = v.trim() || "YYYY-MM-DD";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Daily note folder").setDesc("Folder path inside your vault where daily notes live, e.g. 'Journal/Daily'. Leave empty for vault root.").addText(
      (t) => t.setPlaceholder("Journal/Daily").setValue(this.plugin.settings.dailyNoteFolder).onChange(async (v) => {
        this.plugin.settings.dailyNoteFolder = v.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Connection" });
    new import_obsidian.Setting(containerEl).setName("Test iCloud connection").setDesc("Discover the calendar URL and verify credentials are correct.").addButton(
      (btn) => btn.setButtonText("Test connection").onClick(async () => {
        btn.setButtonText("Testing\u2026");
        btn.setDisabled(true);
        try {
          this.plugin.caldav.reset();
          const url = await this.plugin.caldav.discoverCalendarUrl();
          new import_obsidian.Notice(`\u2713 Connected! Calendar URL found:
${url}`, 8e3);
        } catch (e) {
          new import_obsidian.Notice(`\u2717 ${e instanceof Error ? e.message : String(e)}`, 1e4);
        } finally {
          btn.setButtonText("Test connection");
          btn.setDisabled(false);
        }
      })
    );
  }
};
var CalPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
  }
  async onload() {
    await this.loadSettings();
    this.caldav = new CalDAVClient(this.settings);
    this.registerView(VIEW_TYPE, (leaf) => {
      this.view = new CalendarView(leaf, this);
      return this.view;
    });
    this.addRibbonIcon("calendar", "Open Calendar", () => this.activateView());
    this.addCommand({
      id: "open-calendar",
      name: "Open calendar sidebar",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "refresh-calendar",
      name: "Refresh calendar events",
      callback: () => {
        var _a;
        return (_a = this.view) == null ? void 0 : _a.refresh();
      }
    });
    this.addCommand({
      id: "ot-create-daily",
      name: "Create Daily Note from Calendar",
      callback: () => new CreateDailyModal(this.app, this).open()
    });
    this.addCommand({
      id: "ot-select-event",
      name: "Create Meeting Note (select event)",
      callback: () => new SelectEventModal(this.app, this).open()
    });
    this.addCommand({
      id: "ot-delete-tasks",
      name: "Delete Task Section from Daily Note",
      callback: () => this.deleteTaskSection()
    });
    this.addSettingTab(new CalendarSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    this.caldav = new CalDAVClient(this.settings);
    (_a = this.view) == null ? void 0 : _a.refresh();
  }
  dailyNotePath(date) {
    const fileName = `${formatDate(date, this.settings.dailyNoteFormat)}.md`;
    const folder = this.settings.dailyNoteFolder.trim().replace(/^\/+|\/+$/g, "");
    return folder ? `${folder}/${fileName}` : fileName;
  }
  async loadGeoData() {
    const file = this.app.vault.getAbstractFileByPath("template/geo_data.md");
    if (!(file instanceof import_obsidian.TFile))
      throw new Error("template/geo_data.md not found");
    const geo = JSON.parse(await this.app.vault.read(file));
    if (!geo.default || !geo.location || !geo.location[geo.default]) {
      throw new Error("template/geo_data.md does not contain a valid default location");
    }
    return geo;
  }
  async saveGeoData(geo) {
    const file = this.app.vault.getAbstractFileByPath("template/geo_data.md");
    if (!(file instanceof import_obsidian.TFile))
      throw new Error("template/geo_data.md not found");
    await this.app.vault.modify(file, JSON.stringify(geo, null, 4));
  }
  async readTemplate(name) {
    const file = this.app.vault.getAbstractFileByPath(`template/${name}`);
    if (!(file instanceof import_obsidian.TFile))
      throw new Error(`template/${name} not found`);
    return this.app.vault.read(file);
  }
  async ensureFolder(path) {
    const parts = path.split("/").filter(Boolean);
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (!existing) {
        await this.app.vault.createFolder(current);
      } else if (existing instanceof import_obsidian.TFile) {
        throw new Error(`Cannot create folder "${current}" because a file exists there.`);
      }
    }
  }
  async writeFile(path, content, overwrite) {
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing) {
      if (!(existing instanceof import_obsidian.TFile))
        throw new Error(`Cannot write ${path}: a folder exists there.`);
      if (!overwrite)
        return "skipped";
      await this.app.vault.modify(existing, content);
      return "overwritten";
    }
    const folder = path.split("/").slice(0, -1).join("/");
    if (folder)
      await this.ensureFolder(folder);
    await this.app.vault.create(path, content);
    return "created";
  }
  async openFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile))
      throw new Error(`${path} was not created.`);
    await this.app.workspace.getLeaf(false).openFile(file);
  }
  async fetchOTEvents(dateStr, place) {
    return this.caldav.fetchEventsForDate(dateStr, place.tz);
  }
  async getWeather(dateStr, place) {
    const timeZone = normalizeTimeZone(place.tz);
    const url = `https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(place.lat)}&longitude=${encodeURIComponent(place.lon)}&hourly=weather_code&daily=temperature_2m_max,temperature_2m_min&timezone=${encodeURIComponent(timeZone)}&past_days=7`;
    try {
      const response = await (0, import_obsidian.requestUrl)({ url });
      const data = response.json;
      const index = data.daily.time.indexOf(dateStr);
      if (index === -1)
        return "";
      const maxC = Math.round(data.daily.temperature_2m_max[index]);
      const minC = Math.round(data.daily.temperature_2m_min[index]);
      const maxF = Math.round(maxC * 9 / 5 + 32);
      const minF = Math.round(minC * 9 / 5 + 32);
      const icon = (hour) => {
        var _a;
        return (_a = WEATHER_ICONS[Math.round(data.hourly.weather_code[index * 24 + hour])]) != null ? _a : "";
      };
      return `${maxC}\xB0C/${minC}\xB0C (${maxF}\xB0F/${minF}\xB0F) ${icon(9)}/${icon(15)}/${icon(21)}`;
    } catch (error) {
      console.warn("Obsidian Calendar weather fetch failed:", error);
      return "";
    }
  }
  async deleteTaskSection() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian.Notice("Calendar: No active file.");
      return;
    }
    const content = await this.app.vault.read(file);
    const taskSection = /\n---\nDue Today\n```tasks\n[\s\S]*?```\nCompleted\n```tasks\n[\s\S]*?```(\n|$)/;
    if (!taskSection.test(content)) {
      new import_obsidian.Notice("Calendar: No task section found in this note.");
      return;
    }
    await this.app.vault.modify(file, content.replace(taskSection, "$1"));
    new import_obsidian.Notice("Calendar: Task section deleted.");
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      leaf = (_a = workspace.getRightLeaf(false)) != null ? _a : workspace.getLeaf(true);
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    workspace.revealLeaf(leaf);
  }
};
